// File generated by FlutterFire CLI.
// This is a placeholder - replace with your actual Firebase configuration.
// Run `flutterfire configure` to generate the actual file.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ╔════════════════════════════════════════════════════════════════════╗
  // ║  IMPORTANT: Replace these placeholder values with your actual    ║
  // ║  Firebase project configuration.                                 ║
  // ║                                                                  ║
  // ║  Run: flutterfire configure                                      ║
  // ║  Or get values from Firebase Console > Project Settings           ║
  // ╚════════════════════════════════════════════════════════════════════╝

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgD9ACznei-P8R9PcV0Uh0KQNT2HgK2g',
    appId: '1:624498763954:web:7936a8a1a74d70d82201ab',
    messagingSenderId: '624498763954',
    projectId: 'qget-db',
    authDomain: 'qget-db.firebaseapp.com',
    storageBucket: 'qget-db.firebasestorage.app',
    measurementId: 'G-NMD2W5EHVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLf5bb_PmCfU09lqgJnm_Pt0fRX3J7MRc',
    appId: '1:624498763954:android:43145638029927f12201ab',
    messagingSenderId: '624498763954',
    projectId: 'qget-db',
    storageBucket: 'qget-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChlaCs216DTzxTWytFdXlRy92_nCu7BI',
    appId: '1:624498763954:ios:831e44969e4840ab2201ab',
    messagingSenderId: '624498763954',
    projectId: 'qget-db',
    storageBucket: 'qget-db.firebasestorage.app',
    iosBundleId: 'com.qget.qgetPortal',
  );

}